### ISSUE TITLE
[Doc Feedback] Make Derived and Primary Goals Distinct from eachother

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#240]
"Be sure that your derived goals and your primary goals (as expressed by current situation/needs/ideas) are not too similar. You want to make sure that derived goals do not overlap with your primary goals."

Go over the documentation's primary and derived goals and make sure that they are very distinct from each other

**Comment by JeremySanchez1** [comment]
@irsaris @PinkSylvie Pinged for documentation verification. Section has been added.

**Comment by PinkSylvie** [comment]
Did you remove derived goals to differentiate the derived goals to the current situation?

**Comment by JeremySanchez1** [comment]
Some derived goals overlapped purposes with primary goals, since the main point was to differentiate these parts i decided to remove them. Added new goals more suited towards the long term vision of our application (mental health benefits/community building).

For example, a removed goal was the increase in students motivation. But this is already implicitly stated as one of our primary goals in past sections (needs/ideas). 

@PinkSylvie
