### ISSUE TITLE
[Lecture Topic Task] Usability Testing Documentation

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#261]
Follow up on tasks #259 and #260 to add all the information of the project's use of usability testing into the documentation.

" Explain their test setup, the choice of test
    participants, their monitoring, etc. Also explain their minimal
    expectations for considering the system to suffice. Furthermore,
    they recommended improvements and draw conclusions from their test
    results."

To complete:
As mentioned above add those things to the Milestone 3 document like the rest of the testing methods

**Comment by FrHend-Raul** [comment]
@PinkSylvie Check this task with #259  for completion

**Comment by PinkSylvie** [comment]
Which section and did you add your changes into the change log?

**Comment by PinkSylvie** [comment]
I'm unsure about the validity of in person testing when automation of this test was expected

**Comment by FrHend-Raul** [comment]
What I understood of usability testing was that this type of testing is to verify the usability that the target audience can have using the platform. The way to test this, is to get a sample of tentative users and give them the platform for them to use and  get feedback from them. Then with that feedback I did my conclusions and wrote them on the document. 



![Image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/60901470/34181af9-c29b-40dd-a81e-8c242076fae1) from this page https://www.geeksforgeeks.org/usability-testing/

I believe this is the way to do this type of testing. The only way I see to "automatize" this type of test is to have two or more variants of a part of the platform that we want to test, and provide randomly the different variants to the sample users to see how the feedback changes on this topic specifically. I get this is not a real automatic test, since you need actual persons for the test, but I think the validity of the test is actually the real time user feedback, that is what we look for while doing these tests.

**Comment by FrHend-Raul** [comment]
@PinkSylvie @irsaris The #260 was closed but this one hasn't. Do I need more in the documentation for this and the #259 to be closed?

**Comment by PinkSylvie** [comment]
The merge automatically closes tasks. Sorry for taking a bit to close this one. Great work!
