### ISSUE TITLE
Write User Stories, Epics, Features in documentation

### ISSUE THREAD

**Issue by joel-alvarado** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#52]
**Understanding the Hierarchy:**

- **Epics:** Epics are larger narratives, representing significant chunks of work that cannot be completed within a single sprint. They often follow the format "As a [type of user], I want to [do something] in order to [achieve a goal]." Epics connect to abstract goals relevant to stakeholders.

- **User Stories:** User stories are more granular than epics and provide detailed views of specific functionalities. They can be thought of as the building blocks of an epic, breaking down complex tasks. The format "As a [type of user], I want to [do something] in order to [achieve a goal]" can also be applied to user stories.

**Granularity Considerations:**

- **Avoiding Broadness:** User stories should not be overly broad, such as "As a student, I want to get my enrollment done to have time for more interesting things." Break them down into smaller, more focused user stories to maintain manageability.

- **Avoiding Over-Detailing:** Conversely, user stories should not be overly detailed, like "As a student, I want to click a square button to submit my entries in the current screen." Step back and identify the higher-level task to which this contributes.

**Contextual Meaning:**

- **Connecting to Higher Tasks:** Look for meaning within the student's enrollment tasks. Avoid isolated functionalities and connect user stories to broader tasks or goals in the context of student enrollment.

**Alignment with Stakeholder Goals:**

- **Abstract Goals:** Ensure that epics, user stories, and features are aligned with the abstract goals that stakeholders, based on their roles, would have. This alignment helps prioritize and focus on what truly matters to the stakeholders.

**Finding the Right Balance:**

- **Balancing Act:** Achieving the right granularity involves a balance. Neither too broad nor too detailed, user stories should contribute meaningfully to the overarching epic and align with stakeholder goals.

---

Scoring for this task should have decently high priority, since it relates to the projects documentation.

**Comment by gabrielpadilla7** [comment]
@irsaris I have added this to the documentation. I will copy what I added to this comment. If there's anything that needs to be changed or added, please let me know, otherwise this issue can be closed as completed 

User Stories

As a student, I want to feed my pet by completing flashcard sessions so that it stays healthy and happy.
As a user, I want my pet to grow and evolve as I go through my study sessions to feel a sense of accomplishment.
As a busy learner, I want my pet to remind me of upcoming study sessions to help me stay organized  

Epics

Study Progress Tracking
Description: This epic involves implementing a robust system to track the user’s study progress. It includes monitoring the number of flashcard sessions completed, the topics covered within each session, and the overall proficiency level gained in those topics with each session.
Success Metric: The success of this epic will be measured by the accuracy and comprehension level of the study progress data captured, allowing users to visualize their learning journey and identify areas to improve effectively.

Pet Interaction and Growth
Description: This epic focuses on enhancing user engagement through meaningful interaction with their pet. It includes features such as feeding, customization and facilitation of the pet’s growth and evolution based on the user’s study achievements. 
Success Metric: The success of this epic will be measured by increased user engagement metrics. These include the frequency of interactions with the pet and user satisfaction ratings regarding the pet’s responsiveness and evolution. 

Reminder and Notification System
Description: This epic involves implementing an effective reminder and notification system to keep users informed and engaged in their study routines. These include reminders for upcoming study sessions, notifications for pet care activities and alerts for milestones achieved. 
Success Metric: The success of this epic will be measured by user adherence to study schedules, as indicated by the percentage of completed study sessions prompted by reminders. User feedback regarding the usefulness and timeliness of notifications will be considered in assessing the success. 

Features

Flashcard Session Tracker: Tracks the number of flashcard sessions completed by the user, records study time and monitors proficiency and understanding levels for each topic.

Pet Customization Options: Allows users to customize their pets appearance, name and environment as it evolves and grows with their study progress. 

Reminder Notifications: Sends push notifications to remind users of upcoming study sessions, feeding and care times for the pet and milestones achieved in their learning journey.

**Comment by irsaris** [comment]
Hello, nice work, next time you can copy the link of the section in a google document.
