### ISSUE TITLE
[Lecture Topic Task] Implement a BDD tool into the project code and workflow

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#74]
After Discussing with the team, professor and managers which tool will be added, implement a BDD tool of choice into the project development workflow (Cucumber, Jasmine,…). 

To implement to React Native: https://medium.com/@yusuferenayas/react-behavior-driven-development-with-cucumber-cypress-bdd-245edcfebf87

**Comment by PinkSylvie** [comment]
Hello hope you are doing well! Just reaching out to remind that your task is essential for task #73 which is a task that we need for the doccumentation which is due on Friday

**Comment by diego-velez-upr** [comment]
After talking with @PinkSylvie, we decided to leave the BDD tests as pending for the time being.

This is because of unexpected roadblocks during test implementation, since test logic could not be implemented in time due to an error which prevented us from using production code in the tests, thus rendering them useless for the time being. Nevertheless, TODO comments have been left in the code in order to remind developers that those tests should be implemented in the future. For the time being, the tests exist, but the logic of them have been left pending.

This is the error dealt with when attempting to use production code within the tests.
![image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/98779305/66fd91d7-18a6-46c7-a7eb-5afe4a0589ff)

The tests can be invoked from the terminal via the `npm test` command.

This is how it would look like when all tests pass successfully.
![image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/98779305/50628721-f51c-4f96-bc01-410f7b56d4ce)

This is how it currently looks like with all tests pending.
![image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/98779305/f2c22a91-80f8-468b-b53e-73c39d28673b)

Communication with other developers working on tasks depending on this (#73 and #76) have been carried out in order to notify them of this issue, and give them all the information they need in order to allow them to successfully carry out their work.

**Comment by diego-velez-upr** [comment]
@PinkSylvie @irsaris can ya'll verify this task?

**Comment by PinkSylvie** [comment]
After this task the tool is implemented, just not integrated yet since the tests won't run. Can you create a task on the Developer Board for next milestone in which you'll make sure to get the pending tests running and run it by with the professor then so you can do so. Link that task to this one and the branch issue where your code is at to this one. If @irsaris approves I say we can close this after the above is done

**Comment by diego-velez-upr** [comment]
@PinkSylvie Issue #114 was created in the developer for milestone 2. That issue should finish integrating these tests into the project.

**Comment by PinkSylvie** [comment]
Did you create a repository branch with the current implementation and link it to this and that issue?

**Comment by diego-velez-upr** [comment]
> Did you create a repository branch with the current implementation and link it to this and that issue?

How do I do that? 😅

**Comment by diego-velez-upr** [comment]
> Did you create a repository branch with the current implementation and link it to this and that issue?

I think I managed to do it now.

**Comment by diego-velez-upr** [comment]
> > > Did you create a repository branch with the current implementation and link it to this and that issue?
> > 
> > 
> > I think I managed to do it now.
> 
> Usually is by doing pull requests and linking the task to the issue?

PR #115 was created and linked.

**Comment by PinkSylvie** [comment]
Looks great!
