### ISSUE TITLE
[Lecture Topic Task] Add Examples of the usage of the BDD tool in the dosumentation

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#76]
Document examples of usage of the BDD tool implemented into the project. Recommended to work in hand with the person implementing the tool to get examples to add into the documentation.

**Comment by Fabian-J** [comment]
Some BDD tool specification examples have been provided.

**Comment by PinkSylvie** [comment]
> Some BDD tool specification examples have been provided. 

Where these run with the BDD tool? And screenshots of these being run with the BDD tool

**Comment by Fabian-J** [comment]
While the examples have yet to be run I communicated with the person in charge of task #74 to ensure the examples are aligned with what they plan on testing and how it should work.

**Comment by diego-velez-upr** [comment]
> > Some BDD tool specification examples have been provided.
> 
> Where these run with the BDD tool? And screenshots of these being run with the BDD tool. Please work alongside with task #74 to ensure accurate examples of tests actually run

The tests will be run using `npm test` at the terminal.

This is an example of the output with all the tests passing successfully.
![image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/98779305/d0bf6b34-8603-42e7-9123-21a0c9e2edf0)

This is the current output of the tests, since it has been decided that they should be left pending for the time being.
![image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/98779305/ce7a9572-933f-4cbe-a5c4-25c78e9228cd)

**Comment by PinkSylvie** [comment]
Please add these examples to the documentation

**Comment by Fabian-J** [comment]
The screenshots and comments have been added.

**Comment by PinkSylvie** [comment]
It looks great
